version: '3.8'

services:
  angular-client:
    image: simongjetaj/angular:1.0.0
    container_name: angular-client-container
    build:
      network: host
      context: .
      dockerfile: docker/images/angular/Dockerfile
    ports:
      - '4200:80'
    depends_on:
      - socketio-server

  socketio-server:
    image: simongjetaj/socketio:1.0.0
    container_name: socketio-server-container
    build:
      context: .
      dockerfile: docker/images/node/Dockerfile
    ports:
      - '3000:3000'
