version: '3.8'

services:
  angular-client:
    image: tictactoe/angular
    container_name: angular-client-container
    build:
      network: host
      context: .
      dockerfile: docker/images/angular/Dockerfile
    ports:
      - '4200:80'
    depends_on:
      - socketio-server
    networks:
      - angular-client

  socketio-server:
    image: tictactoe/socketio
    container_name: socketio-server-container
    build:
      context: .
      dockerfile: docker/images/node/Dockerfile
    ports:
      - '3000:3000'
    networks:
      - socketio-server

networks:
  angular-client:
    driver: bridge
  socketio-server:
    driver: bridge
