apiVersion: v1
kind: ConfigMap
metadata:
  name: angular-config
data:
  config.json: "{\r\n  \"SERVER_BASE_URL\": \"http://localhost:30101\"\r\n}\r\n"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: tic-tac-toe
    tier: frontend
    track: stable
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tic-tac-toe
      tier: frontend
      track: stable
  template:
    metadata:
      labels:
        app: tic-tac-toe
        tier: frontend
        track: stable
    spec:
      containers:
        - name: angular-client
          image: simongjetaj/angular:1.0.0
          ports:
            - containerPort: 80
          volumeMounts:
            - name: angular-config-volume
              mountPath: /usr/share/nginx/html/assets/config
      volumes:
        - name: angular-config-volume
          configMap:
            name: angular-config

---
apiVersion: v1
kind: Service
metadata:
  name: angular-service
spec:
  type: NodePort
  selector:
    app: tic-tac-toe
    tier: frontend
    track: stable
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30100
