apiVersion: v1
kind: ConfigMap
metadata:
  name: socketio-config
data:
  CLIENT_BASE_URL: http://localhost:30100
  RATE_LIMIT_WINDOW_MS: '900000'
  RATE_LIMIT_MAX: '100'

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: tic-tac-toe
    tier: backend
    track: stable
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tic-tac-toe
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: tic-tac-toe
        tier: backend
        track: stable
    spec:
      containers:
        - name: socketio-server
          image: simongjetaj/socketio:1.0.0
          ports:
            - name: http
              containerPort: 3000
          envFrom:
            - configMapRef:
                name: socketio-config

---
apiVersion: v1
kind: Service
metadata:
  name: socketio-service
spec:
  type: NodePort
  selector:
    app: tic-tac-toe
    tier: backend
    track: stable
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30101
